<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <RepositoryUrl>https://github.com/majorsilence/MPlayerControl</RepositoryUrl>
    <Version>27.0.0</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Product>Majorsilence Media</Product>
    <Copyright>Copyright © 2026 majorsilence (Peter Gill) and other contributors</Copyright>
    <LangVersion>latest</LangVersion>
    <Description>Media player control and server for dotnet.  Winforms, avalonia, uno desktop controls for playback via mplayer or mpv.  
    Server side process video files using ffmpeg.</Description>
  </PropertyGroup>
</Project>