<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.0.0" />
    <PackageVersion Include="Avalonia" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    <PackageVersion Include="NUnit" Version="4.4.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="3.6.1" />
    <PackageVersion Include="NUnit.Runners" Version="3.12.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.1.0" />
    <PackageVersion Include="NunitXml.TestLogger" Version="6.1.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.0.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="7.3.1" />
    <PackageVersion Include="UUIDNext" Version="2.0.2" />
  </ItemGroup>
</Project>
