<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageVersion Include="Avalonia" Version="12.0.2" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.3" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="NUnit" Version="4.5.1" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.12.0" />
    <PackageVersion Include="NUnit.Runners" Version="3.12.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="NunitXml.TestLogger" Version="8.0.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageVersion Include="UUIDNext" Version="4.2.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Majorsilence.Forms" Version="26.0.32" />
    <PackageVersion Include="Majorsilence.Forms.Avalonia" Version="26.0.32" />
  </ItemGroup>
</Project>