
// This file has been generated by the GUI designer. Do not modify.
namespace MPlayerGtkWidget
{
	public partial class GtkMPlayerWidget
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.DrawingArea drawingareaVideo;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button buttonStop;
		
		private global::Gtk.Button buttonPlay;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MPlayerGtkWidget.GtkMPlayerWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MPlayerGtkWidget.GtkMPlayerWidget";
			// Container child MPlayerGtkWidget.GtkMPlayerWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.drawingareaVideo = new global::Gtk.DrawingArea ();
			this.drawingareaVideo.Name = "drawingareaVideo";
			this.vbox3.Add (this.drawingareaVideo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.drawingareaVideo]));
			w1.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonStop = new global::Gtk.Button ();
			this.buttonStop.CanFocus = true;
			this.buttonStop.Name = "buttonStop";
			this.buttonStop.UseUnderline = true;
			this.buttonStop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
			this.hbox2.Add (this.buttonStop);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonStop]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonPlay = new global::Gtk.Button ();
			this.buttonPlay.CanFocus = true;
			this.buttonPlay.Name = "buttonPlay";
			this.buttonPlay.UseUnderline = true;
			this.buttonPlay.Label = global::Mono.Unix.Catalog.GetString ("Play");
			this.hbox2.Add (this.buttonPlay);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonPlay]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonStop.Clicked += new global::System.EventHandler (this.OnButtonStopClicked);
			this.buttonPlay.Clicked += new global::System.EventHandler (this.OnButtonPlayClicked);
		}
	}
}
