name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: cd Release-Builds && ./build-release.sh
    - name: Build
      run: dotnet build TownSuite.Web.SSV3Facade.sln --no-restore
    - name: Test
      run: dotnet test TownSuite.Web.SSV3Facade.sln --no-build --verbosity normal
