name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: cd src && dotnet build Majorsilence.Winforms.MPlayerControl.sln

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: run: cd src && dotnet build Majorsilence.Avalonia.UI.sln
    - name: Install mplayer and mencoder
      run: sudo apt-get install -y mplayer mencoder
    - name: Test
      run: dotnet vstest "src/MplayerUnitTests/bin/Release/net6.0/MplayerUnitTests.dll" --logger:"nunit;LogFileName=src/MplayerUnitTests/bin/Release/net6.0/nunit-result.xml"

